### ISSUE TITLE
Documentation enrichment

### ISSUE THREAD

**Issue by cparaskeva** [giovannicandido/slush-spring-aurelia#4]
Please provide some clear guidedlines on how to run client/server applications.

**Comment by giovannicandido** [comment]
I have created some documentation in **templates/docs** folder, which is copied to project on generation. Please, ping me if find something more specific to improve in the docs 👍

**Comment by cparaskeva** [comment]
You have done good work here however it is a pitty not to have the appropriate documentation for runing & testing the application. I have took a look on the documentation however I cannot figure out a linear compilation process. e.g. for the server side you can follow steps  A,B,C, for client side X,Y,Z

**Comment by giovannicandido** [comment]
Now I get it.
I will provide a linear step documentation to get started quickly

**Comment by giovannicandido** [comment]
@cparaskeva I recently create the doc https://github.com/giovannicandido/slush-spring-aurelia/blob/master/copy/docs/quickstart.md

What do you think?

Note: I'm thinking this project is getting over complicated, I will try to easy steps in https://github.com/giovannicandido/generator-spring-spa

**Comment by giovannicandido** [comment]
I forgot to mention that I have fixed a bug in generator which not copy some files, update with `npm install -g slush-spring-aurelia`

**Comment by cparaskeva** [comment]
Excellent work! The documentation is now very comprehensive! Thank you.
